### ISSUE TITLE
3- Todo class 

### ISSUE THREAD

**Issue by samirm00** [samirm00/todo-lists-restful-pjs#4]
- [x] this issue developed on a branch `2-class`.
- [x] create a file `todo.js`
- [x] `POST` todo  , fetch all `todos`, convert the response to j son object 
- [x] `GET` one todo , fetch a todo by `id` and convert the response to j son object 
- [x] `GET` all todos , fetch all todos and convert the response to j son object 
- [x] `PATCH` a todo , fetch a todo by `id`, modify the body and  convert the response to j son object 
- [x] `update`todos  etch all all tods , render them and append them to the `div` root
- [x] `renderTodo` , create anew `div` parent , `li`,`completedButton`, `editButton`,`deleteButton` and add event listener to three.
- [x] `renderTodos`  create anew `div` and `ul` map throw all todos and render each using `renderTodo`
