### ISSUE TITLE
4- add todo handler 

### ISSUE THREAD

**Issue by samirm00** [samirm00/todo-lists-restful-pjs#5]
- [x] this issue developed in a branch `3-addTodo`
- [x] create a file `handleAddTodo.js`
- [x] import the class `Todo`
- [x] create a new todo instance
- [x] `POST` todo and render it 
- [x] appended to the `root`
