### ISSUE TITLE
7-listener Add Todo

### ISSUE THREAD

**Issue by samirm00** [samirm00/todo-lists-restful-pjs#8]
- [x] this issue developed on a branch `3-addTodo`
- [x] import `handleAddTod` handler 
- [x]  get `input = button` add todo and add event listener
